### ISSUE TITLE
[bug] Incorrect display of colors

### ISSUE THREAD

**Issue by tmschorr** [Pilzinsel64/PlayerTags#10]
The colors of the tags are the same as the colors of the player names and not as it should be that e.g. the healer tag is displayed in green.

**Comment by Pilzinsel64** [comment]
Will be fixed with v1.6.2.

**Comment by Pilzinsel64** [comment]
https://github.com/goatcorp/DalamudPluginsD17/pull/378

**Comment by Pilzinsel64** [comment]
Well, it's not fixed yet. I found the issue.
It is not fixable. As long as the tag has a color it got applied even in chat to the tag. Everything that comes behind the tag will have the default color
Workaround: set the tag position in chat to the end (right).
