### ISSUE TITLE
Is it possible to have the option to only get the tags in chat, and not replace the titles above players?

### ISSUE THREAD

**Issue by rebelsong42** [Pilzinsel64/PlayerTags#11]
I love the tags that show up next to the names in chat, and don't really need to see what jobs people are out in the world. However, no matter if I set the job title to visible or not visible, there is no way to see the titles that other players have set. It might seem minor, but I enjoy coming across titles I hadn't seen before. Is this a possibility for an option? Or more trouble than it's worth?

**Comment by Pilzinsel64** [comment]
Hm... On the first tab in the settings, put the option for the title to "Default". In the second tab, disable the option that says that the Tag should be shown in nameplate. There should be an option for that. Alternatively you can set where the tag should be added. Change that to "name" and set the position to "before/start"
If you don't get a solution for then I can check that tomorrow and make a screenshot for. But until then, just try a bit, there mustbe a solution for. ^^
