### ISSUE TITLE
Tags on the local player don't work

### ISSUE THREAD

**Issue by RokasKil** [Pilzinsel64/PlayerTags#13]
Whenever you get targeted in chat messages with things like `<t>` or `<me>` the message gets garbled.

For example this is what I get when using `prefix <me> suffix`

![paveikslas](https://user-images.githubusercontent.com/55197768/191567150-9a9735bc-74ee-4fd9-860d-e488eee9803d.png)

There used to be a checkmark to not include yourself in tagging to workaround this issue but it's gone now, even with "Show for self" property unchecked I get something like this

![paveikslas](https://user-images.githubusercontent.com/55197768/191567520-36bcc3b9-c152-4aee-a286-f260366db7e9.png)

**Comment by Pilzinsel64** [comment]
Ah yes, I've fixed that bug today for v1.7.4.
There is a pull request for the update but not merged yet. Probably get merged today or latest tomorrow. https://github.com/goatcorp/DalamudPluginsD17/pull/532
