### ISSUE TITLE
Unable to exclude myself?

### ISSUE THREAD

**Issue by Sinterra79** [Pilzinsel64/PlayerTags#17]
This plugin is incredibly useful but I'd like to be able to exclude myself from it's function so I can still see my own title since I already know what Job I'm playing. Is there any way to do this? I've tried tinkering with the config but can't seem to find a way, I may be looking in the wrong place.

**Comment by Pilzinsel64** [comment]
It is possible, of course!
Either you select the Tag "Role" and add the following property overwrite, or you just select the Tag "All". Wherever you need this.

1. Select tag of your choice (and and the property to overwrite):
![grafik](https://user-images.githubusercontent.com/23138465/203322301-3a6c63c7-1653-4de9-9cdc-d337026d3e65.png)

2. Scroll down. Here toogle this to off:
![grafik](https://user-images.githubusercontent.com/23138465/203322693-c820a09b-0a6d-4c8b-b7b1-49f762e2e2e9.png)

Please let me know if this solves your question! :)

**Comment by Sinterra79** [comment]
That solved it! Thank you so much I appreciate it the swift reply! <3
