### ISSUE TITLE
Cant see title

### ISSUE THREAD

**Issue by basement0** [Pilzinsel64/PlayerTags#18]
I seemingly cannot get titles to appear regardless of plug-in configuration.

**Comment by Pilzinsel64** [comment]
Did you teleport to another location after changing the configuration? The configuration can't take effect instantly as the game decides itself when it's time to update the nameplate of a player.

**Comment by basement0** [comment]
Yes, I’ve restarted the game as well on different settings.

**Comment by Pilzinsel64** [comment]
Alright, will double check it soon.

**Comment by basement0** [comment]
Thanks!

**Comment by Pilzinsel64** [comment]
Alright, I checked it yet within the 20 minutes left xD

The option works. I can't reproduce your issue sadly.
What I tried:
- In-game option to "Visible" and plugin-option to "Never"
  - Result: It's hidden, as expected.
- In-game option to "Hidden" and plugin-option to "Default"
  - Result: It's hidden, as expected.
- In-game option to "Visible" and plugin-option to "Default"
  - Result: It's visible, as expected.

I also checked the code, it's seems to be fine.

Did you change that option for "Everywhere" or only for a specific activity context, like PvE? Remember that you need to adjust every set (PvE, Overworld, PvP) when choosing using "Everywhere" (everywhere just overwrites all other sets).

**Comment by d-lindahl** [comment]
For anyone landing here because titles aren't showing:
The default setting for "Position in nameplates" is "replace" and the default "Target in nameplates" is title so title will be replaced by the player tag if this is not changed.
![image](https://user-images.githubusercontent.com/690410/232169906-8ca93f11-ba46-41d5-8b0f-d223417113ac.png)
