### ISSUE TITLE
Suggestion: Option to allow GPose icon to override the job icon.

### ISSUE THREAD

**Issue by RorschachsDream** [Pilzinsel64/PlayerTags#2]
The base game has a camera icon when someone is in GPose, unfortunately the job icon is in the same spot and overrides the GPose icon, rendering you unable to tell when someone is GPosing unless they're on your friends and you check the friends list.

I'd like an option to let the GPose icon either override the job icon, or appear next to it, so I can tell when people are GPosing. :)

**Comment by RorschachsDream** [comment]
Oh my god I'm stupid this is the wrong plugin LOL, my bad.

**Comment by Pilzinsel64** [comment]
No problem. ;)
