### ISSUE TITLE
[Suggestion] Allow to change nameplate size

### ISSUE THREAD

**Issue by Guilhem30** [Pilzinsel64/PlayerTags#5]
It would be nice if we were able to modify the size of the nameplate text.
The base game allow to change it with 3 different options but the smallest size is still too big for people playing on a low resolution (like under 1080p)

Would it be possible to add this ?

**Comment by Pilzinsel64** [comment]
Hm, not sure. The problem with sizing I also have in #1. It's not possible on this way I guess. It may be possible on overwriting the system settings, but then it make more sense to be an option in the `Simple Tweaks` plugin. 🤔
Could check again, if it's possible somehow to resize the text of the nameplate, but I assume that not.

**Comment by Pilzinsel64** [comment]
Did some research but sadly it's not possible. The game seems not to have that feature for setting the font size within the nameplate, only for the whole nameplate via the client settings.
