### ISSUE TITLE
Disabling chat name colors overrides Simpletweaks plugin

### ISSUE THREAD

**Issue by Dranni21312** [Pilzinsel64/PlayerTags#8]
Disabling role-specific chat name colors causes the color of names to be the default, despite another plugin (SimpleTweaks) forcing assigned chat name colors.

**Comment by Dranni21312** [comment]
To be more specific, when this option is disabled:

![image](https://user-images.githubusercontent.com/80227585/188043083-535a9e78-c6e8-4adb-a8a4-4f12de532b57.png)

Then ideally, settings such as this one in Simple Tweaks, should work without an issue:

![image](https://user-images.githubusercontent.com/80227585/188043167-e90f53ff-0c8b-4d4b-b7ad-70696077093c.png)

However, currently, disabling that option in Player Tags plugin, forces the colors to be default instead of letting other plugins control them.

**Comment by Pilzinsel64** [comment]
Probably fixed with https://github.com/goatcorp/DalamudPluginsD17/pull/370

**Comment by Pilzinsel64** [comment]
Well, it's not fixed yet. I found the issue.
It is not fixable. As long as the tag has a color it get applied even in chat to the tag. Everything that comes behind the tag will have the default color. Before the tag there is a "start this color" and behind the tag there is a "start with color" where the second one will reset to default color.
Every other plugin that then tries to set another color will do that at the start and end of the text and not for every single partb of it. Latest after the tag where the color get tested the color from other plugins is lost.
Workaround: set the tag position in chat to the end (right). So, the color of other plugins will affect the whole text, except the last part at the end, the tag.
